#+title: ephone.el
#+author: Justin Andreas Lacoste
#+email: me@justin.cx

Control the telephony stack of your smartphone from inside Emacs
via [[https://git.kernel.org/pub/scm/network/ofono/ofono.git/about/][ofono]] and Bluetooth.

* Features

+ Hangup calls & and dial phone-numbers.
+ Answer incoming calls.
+ Hooks for various actions.
+ =tel:= Org-links
+ Supports multiple phones.
+ Supports multiple HCI Bluetooth controllers.

* Demo

#+html: <video loop autoplay controls src="https://github.com/27justin/ephone.el/assets/72092018/46384009-7e8e-457b-9882-2330fef07f80"></video>

* Installation

#+BEGIN_QUOTE
INFO: Please make sure you have both D-BUS and [[https://git.kernel.org/pub/scm/network/ofono/ofono.git/about/][ofonod]] installed and running before following along.
#+END_QUOTE

You can install ephone.el through git:

#+BEGIN_SRC bash
  git clone https://github.com/27justin/ephone.el ~/.emacs.d/site-lisp/ephone.el
#+END_SRC

Then add the path to your ~load-path~ and ~(require)~ the package.
#+BEGIN_SRC elisp
  (add-to-list 'load-path "~/.emacs.d/site-lisp/ephone.el")
  (require 'ephone)
  (ephone--attach-dbus-hooks)
  #+END_SRC

After which you can re-evaluate your config, or restart Emacs.

* Usage

ephone.el's interactive functions are prefixed with *ephone/*.

Here an overview of said functions.
#+BEGIN_SRC elisp
  (ephone/dial "<number>")
  (ephone/dial-last-number)
  (ephone/hangup) ;; Also used to reject incoming calls.
  (ephone/answer)
#+END_SRC

** Hooks

ephone.el provides the following hooks
#+BEGIN_SRC elisp
  ephone-call-hook   ;; Runs when a call is either started or received.
  ephone-hangup-hook ;; Runs when a call is ended.
#+END_SRC

* Examples

** Open a Capture-Buffer on incoming calls

A prominent use-case may be clocking out of the current org-task and starting a capture buffer whenever a call is received, or started.

#+BEGIN_SRC elisp
(add-to-list 'org-capture-templates ("p" "Call" entry
    (file+headline "~/org/TASKS.org" "Calls")
    "* %T %(ephone/get-phone-number)\n#+BEGIN_SRC elisp\n(ephone/hangup)\n#+END_SRC\n\n    %?"
    :clock-resume t :clock-in t))
(defun capture-received-call ()
    (org-capture nil "p"))
(add-hook ephone-call-hook #'capture-received-call)
#+END_SRC

** Store HTML =tel:= inside org and immediately call them

Another fairly useful feature are ~tel:~ org-links, with similar semantics to the ~href~ Attribute on HTML A-tags
for those familiar.
Running ~C-c C-o~ / ~org-open-at-point~ on these links will run ~ephone/dial~ with the given number.
